-- 유튜버 추천 장소 시드 데이터 (2026-07-09 데모 수집분, 9건)
insert into public.youtuber_places
  (name, address, latitude, longitude, category, info, thumbnail_url, youtuber, rating_note, source_video_url, source_type, confidence, extra)
values
  ('히모카와 키류 이케부쿠로점 (ひもかわ桐生)', 'Tokyo, Toshima City, Minamiikebukuro 3-18-35 橋本荘 101', NULL, NULL, '우동', '손가락 두 개 너비의 납작면. 매장에서 직접 뽑는 면이라 탄력 있음. 따뜻한 육수 츠케 스타일 추천. 영업 11:00-15:30/18:00-21:00(월휴), 메뉴: 네기 츠케 히모카와 우동 1,090엔 / 상 텐푸라 모둠 860엔', 'https://i.ytimg.com/vi/fgqilIjn378/maxresdefault.jpg', 'Space Tamnik (공간탐닉)', '설명/고정댓글에 직접 정리된 정보 (평점 수치는 아님, 창작자 큐레이션)', 'https://www.youtube.com/shorts/fgqilIjn378', 'shorts', 'high', '{"source_url": "https://www.youtube.com/shorts/fgqilIjn378", "source_type": "shorts", "confidence": "high"}'::jsonb),
  ('키츠네야', 'Tokyo, Chuo City, Tsukiji 4-9-12', NULL, NULL, '덮밥/규동', '77년 된 도쿄 츠키지 시장 맛집. 소고기/내장을 뭉근하게 끓인 덮밥. 영업 06:30-13:30(수,일휴), 메뉴: 규동 800엔 / 호르몬동(내장덮밥) 900엔 / 계란추가 100엔', 'https://i.ytimg.com/vi/5ve6DmveFqM/maxresdefault.jpg', 'Space Tamnik (공간탐닉)', '설명/고정댓글에 직접 정리된 정보', 'https://www.youtube.com/shorts/5ve6DmveFqM', 'shorts', 'high', '{"source_url": "https://www.youtube.com/shorts/5ve6DmveFqM", "source_type": "shorts", "confidence": "high"}'::jsonb),
  ('리키마루 로바타야키', '오사카 텐노지', NULL, NULL, '로바타야키(꼬치구이)', '화로에서 바로 구워주는 로바타구이. 가리비 버터구이 추천(2번 주문 권장). 관광객 적고 현지인 줄 서는 곳으로 소개됨.', 'https://i.ytimg.com/vi/xEFljIfz8Qw/maxresdefault.jpg', '우미관 (osaka544)', '"현지인 줄 서고 맛으로 승부 보는 집" - 창작자 큐레이션 문구', 'https://www.youtube.com/shorts/xEFljIfz8Qw', 'shorts', 'medium(정확주소 미포함, 지역명만)', '{"source_url": "https://www.youtube.com/shorts/xEFljIfz8Qw", "source_type": "shorts", "confidence": "medium(정확주소 미포함, 지역명만)"}'::jsonb),
  ('다이코 스시 본점', '오사카 신세카이', NULL, NULL, '스시(회전초밥)', '150엔부터 시작하는 가성비. 네타 60종 이상. 현지인 웨이팅 맛집으로 소개.', 'https://i.ytimg.com/vi/xEFljIfz8Qw/maxresdefault.jpg', '우미관 (osaka544)', '"미친 가성비" - 창작자 큐레이션 문구', 'https://www.youtube.com/shorts/xEFljIfz8Qw', 'shorts', 'medium', '{"source_url": "https://www.youtube.com/shorts/xEFljIfz8Qw", "source_type": "shorts", "confidence": "medium"}'::jsonb),
  ('오사카 돈카츠', '오사카 아베노 HOOP', NULL, NULL, '돈카츠', '두께감 있는 카츠. 저온조리로 육즙이 풍부함.', 'https://i.ytimg.com/vi/xEFljIfz8Qw/maxresdefault.jpg', '우미관 (osaka544)', '"육즙 폭발, 한 끼로 끝" - 창작자 큐레이션 문구', 'https://www.youtube.com/shorts/xEFljIfz8Qw', 'shorts', 'medium', '{"source_url": "https://www.youtube.com/shorts/xEFljIfz8Qw", "source_type": "shorts", "confidence": "medium"}'::jsonb),
  ('너의 이름은 성지 (신카이 마코토 작품)', 'https://goo.gl/maps/HeBHaj4XRm8ZBWZN8 (신주쿠)', NULL, NULL, '애니메이션 성지순례', '애니메이션 ''너의 이름은'' 배경이 된 신주쿠 실제 촬영 스팟.', 'https://i.ytimg.com/vi/hmqXjQ8yUW0/maxresdefault.jpg', '구부의 도쿄 가이드 (Gubu in the Tokyo)', NULL, 'https://www.youtube.com/watch?v=hmqXjQ8yUW0', 'long_form(고정댓글)', 'high(정확한 지도링크 고정댓글 제공)', '{"source_url": "https://www.youtube.com/watch?v=hmqXjQ8yUW0", "source_type": "long_form(고정댓글)", "confidence": "high(정확한 지도링크 고정댓글 제공)"}'::jsonb),
  ('언어의 정원 성지 (신카이 마코토 작품)', 'https://goo.gl/maps/s5p2vsn1NtsJEaZW8 (신주쿠)', NULL, NULL, '애니메이션 성지순례', '애니메이션 ''언어의 정원'' 배경이 된 신주쿠 실제 촬영 스팟.', 'https://i.ytimg.com/vi/hmqXjQ8yUW0/maxresdefault.jpg', '구부의 도쿄 가이드 (Gubu in the Tokyo)', NULL, 'https://www.youtube.com/watch?v=hmqXjQ8yUW0', 'long_form(고정댓글)', 'high', '{"source_url": "https://www.youtube.com/watch?v=hmqXjQ8yUW0", "source_type": "long_form(고정댓글)", "confidence": "high"}'::jsonb),
  ('봇치 더 락 성지 + 라이브하우스', 'https://goo.gl/maps/gwktdRQbVXimBjnE8 (시모키타자와)', NULL, NULL, '애니메이션 성지순례', '애니메이션 ''봇치 더 락'' 배경이 된 시모키타자와 실제 스팟. 실제 라이브하우스 공연 스케줄/티켓 구매 링크까지 고정댓글에 포함.', 'https://i.ytimg.com/vi/hmqXjQ8yUW0/maxresdefault.jpg', '구부의 도쿄 가이드 (Gubu in the Tokyo)', NULL, 'https://www.youtube.com/watch?v=hmqXjQ8yUW0', 'long_form(고정댓글)', 'high', '{"source_url": "https://www.youtube.com/watch?v=hmqXjQ8yUW0", "source_type": "long_form(고정댓글)", "confidence": "high"}'::jsonb),
  ('라멘 카네카츠 (らーめん かねかつ)', '(도쿄, 리다이렉트로 확인)', 35.871742, 139.6470167, '라멘', '카라미가 ''도쿄 1위''로 소개한 라멘집. 닭고기를 두부처럼 가공한 특이 메뉴.', 'https://i.ytimg.com/vi/3ui8xDDPfro/maxresdefault.jpg', '카라미', NULL, 'https://www.youtube.com/watch?v=3ui8xDDPfro', 'long_form', 'medium', '{"source_url": "https://www.youtube.com/watch?v=3ui8xDDPfro", "source_type": "long_form", "confidence": "medium"}'::jsonb);
